version: '3.4'

services:
  db: 
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=passwordSQL
      - MSSQL_PID=Express

  webstore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB__Type=DockerDB
    ports:
      - "80"
