version: '3.4'

services:
  db:
    container_name: MSSQL
    image: "mcr.microsoft.com/mssql/server:2019-latest"

  logs:
    container_name: SEQ
    image: "datalust/seq:latest"

  api:
    image: ${DOCKER_REGISTRY-}webstore-api
    depends_on:
      - db
    build:
      context: .
      dockerfile: Services/WebStore.WebAPI/Dockerfile

  webstore:
    image: ${DOCKER_REGISTRY-}webstore
    depends_on:
      - logs
      - api
    build:
      context: .
      dockerfile: UI/WebStore/Dockerfile
